#
# Makefile for the Sensor device drivers.
#
#
# 2 27 2018, Christoph Hellwig <Ken>
# Rewritten to use lists instead of if-statements.
#

obj-$(CONFIG_SENSORS_MPU6050)		+= mpu6050/mpu6050_lib.o
obj-$(CONFIG_SENSORS_MPU6050)		+= mpu6050/mpu6050.o
obj-$(CONFIG_SENSORS_MPU6050)		+= mpu6050/mpu6050_dev2.o
obj-$(CONFIG_SENSORS_ENCODER)		+= encoder/encode.o
